/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Archivos.ArregloRegistros;
import Administrativo.ArregloUbigeo;
import Atxy2k.CustomTextField.RestrictedTextField;
import Clases.DatosLaborales;
import Clases.Direccion;
import Clases.Fecha;
import Clases.Registro;

import Clases.Usuario;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author bryleo
 */
public class ActualizacionDatos extends javax.swing.JInternalFrame {
ArregloRegistros a=new ArregloRegistros();
 ArregloUbigeo u = new ArregloUbigeo();
    /**
     * Creates new form ActualizacionDatos
     */
    public ActualizacionDatos() {
        initComponents();
        ValoresIniciales();
        AsignacionValores();
        Limitadores();
        btnG1.setVisible(false);
        btnG2.setVisible(false);
        btnG3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNombreCli = new javax.swing.JTextField();
        txtDniCli = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbMasCli = new javax.swing.JRadioButton();
        rbFemCli = new javax.swing.JRadioButton();
        dataFechaCli = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        txtZona = new javax.swing.JTextField();
        txtVia = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtMz = new javax.swing.JTextField();
        txtLote = new javax.swing.JTextField();
        cbDepar = new javax.swing.JComboBox<>();
        cbProvin = new javax.swing.JComboBox<>();
        cbDistrito = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtComercial = new javax.swing.JTextField();
        txtActividad = new javax.swing.JTextField();
        txtOficio = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnModi1 = new javax.swing.JButton();
        btnG1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnModi2 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnModi3 = new javax.swing.JButton();
        btnG3 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS PERSONALES"));

        txtNombreCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres Completos"));

        txtDniCli.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Género"));

        grupoSexo.add(rbMasCli);
        rbMasCli.setText("Masculino");

        grupoSexo.add(rbFemCli);
        rbFemCli.setText("Femenino");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMasCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(rbFemCli)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMasCli)
                    .addComponent(rbFemCli))
                .addContainerGap())
        );

        dataFechaCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Nacimiento"));
        dataFechaCli.setDateFormatString("dd/MM/yy");
        dataFechaCli.setMaxSelectableDate(new java.util.Date(1009778500000L));
        dataFechaCli.setMinSelectableDate(new java.util.Date(-473363900000L));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreCli)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDniCli, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataFechaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniCli, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataFechaCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DOMICILIO"));

        txtZona.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo & Nombre de Zona"));

        txtVia.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo & Nombre de Via"));

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("N°"));

        txtMz.setBorder(javax.swing.BorderFactory.createTitledBorder("Mz"));

        txtLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Lt"));

        cbDepar.setBorder(javax.swing.BorderFactory.createTitledBorder("DEPARTAMENTO"));
        cbDepar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDeparMouseClicked(evt);
            }
        });
        cbDepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeparActionPerformed(evt);
            }
        });

        cbProvin.setBorder(javax.swing.BorderFactory.createTitledBorder("PROVINCIA"));
        cbProvin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbProvinMouseClicked(evt);
            }
        });
        cbProvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProvinActionPerformed(evt);
            }
        });

        cbDistrito.setBorder(javax.swing.BorderFactory.createTitledBorder("DISTRITO"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProvin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtZona)
                    .addComponent(txtVia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMz, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProvin)
                            .addComponent(cbDistrito)
                            .addComponent(cbDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS LABORALES"));

        txtComercial.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Comercial"));

        txtActividad.setBorder(javax.swing.BorderFactory.createTitledBorder("Actividad Económica"));

        txtOficio.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficio"));

        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));

        txtCelular.setBorder(javax.swing.BorderFactory.createTitledBorder("Celular"));

        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComercial)
                    .addComponent(txtActividad)
                    .addComponent(txtOficio)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOficio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnModi1.setText("MODIFICAR");
        btnModi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModi1ActionPerformed(evt);
            }
        });

        btnG1.setText("GUARDAR");
        btnG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnG1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnModi2.setText("MODIFICAR");
        btnModi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModi2ActionPerformed(evt);
            }
        });

        btnG2.setText("GUARDAR");
        btnG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnModi2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnG2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnG2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnModi3.setText("MODIFICAR");
        btnModi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModi3ActionPerformed(evt);
            }
        });

        btnG3.setText("GUARDAR");
        btnG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnModi3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnG3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModi3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnG3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel4);

        getContentPane().add(jScrollPane3);

        setBounds(0, 0, 709, 515);
    }// </editor-fold>//GEN-END:initComponents
    
    void ValoresIniciales()
    {
        txtActividad.setEnabled(false); 
        txtCelular.setEnabled(false);
        txtComercial.setEnabled(false);
        txtCorreo.setEnabled(false);
        cbProvin.setEnabled(false);
        cbDistrito.setEnabled(false);
        txtDniCli.setEnabled(false);
        txtLote.setEnabled(false);
        txtMz.setEnabled(false);
        txtNombreCli.setEnabled(false);
        txtNumero.setEnabled(false);
        txtOficio.setEnabled(false);
        cbDepar.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtZona.setEnabled(false);
        txtVia.setEnabled(false);
        rbFemCli.setEnabled(false);
        rbMasCli.setEnabled(false);
        dataFechaCli.setEnabled(false);
        //datos
        btnG1.setVisible(false);
        btnG2.setVisible(false);
        btnG3.setVisible(false);
        btnModi1.setVisible(true);
        btnModi2.setVisible(true);
        btnModi3.setVisible(true);
    }
    void AsignacionValores()
    {
        txtDniCli.setText(Registro.unregistro.getUsuario().getDNI());
        txtNombreCli.setText(Registro.unregistro.getUsuario().getNombre());
        int día = Registro.unregistro.getUsuario().getFechaNacimiento().getDia();
        int mes = Registro.unregistro.getUsuario().getFechaNacimiento().getMes();
        int anio = Registro.unregistro.getUsuario().getFechaNacimiento().getAnio();
        Date fechaNacimiento = new Date();
        fechaNacimiento.setDate(día);
        fechaNacimiento.setMonth(mes);
        fechaNacimiento.setYear(anio);
        dataFechaCli.setDate(fechaNacimiento);
        if(Registro.unregistro.getUsuario().getSexo().equals("Masculino"))
        {
            rbMasCli.setSelected(true);
        }
        else
        {
            rbFemCli.setSelected(true);
        }
        
        txtVia.setText(Registro.unregistro.getUsuario().getDomicilio().getTipo_NombreVia());
        txtZona.setText(Registro.unregistro.getUsuario().getDomicilio().getTipo_NombreZona());
        txtNumero.setText(String.valueOf(Registro.unregistro.getUsuario().getDomicilio().getNumero()));
        txtMz.setText(Registro.unregistro.getUsuario().getDomicilio().getManzana());
        txtLote.setText(Registro.unregistro.getUsuario().getDomicilio().getLote());
        txtComercial.setText(Registro.unregistro.getLoborales().getNombreComercial());
        txtActividad.setText(Registro.unregistro.getLoborales().getActividadEconomica());
        txtOficio.setText(Registro.unregistro.getLoborales().getOficio());
        txtTelefono.setText(Registro.unregistro.getLoborales().getTelefono());
        txtCelular.setText(Registro.unregistro.getLoborales().getCelular());
        txtCorreo.setText(Registro.unregistro.getLoborales().getCorreo());
        CargarDepar();
        cbDepar.setSelectedItem(Registro.unregistro.getUsuario().getDomicilio().getDepartamento());
        cbProvin.setSelectedItem(Registro.unregistro.getUsuario().getDomicilio().getProvincia());
        cbDistrito.setSelectedItem(Registro.unregistro.getUsuario().getDomicilio().getDistrito());
        
    }
    void Limitadores()
    {
        Limitador(txtNombreCli, 200);
        Limitador(txtDniCli,8);
        
        Limitador(txtZona, 200);
        Limitador(txtVia, 200);
        Limitador(txtMz, 4);
        Limitador(txtLote, 4);
        Limitador(txtNumero, 6);
        Limitador(txtComercial, 250);
        Limitador(txtActividad, 250);
        Limitador(txtOficio, 250);
        Limitador(txtTelefono, 15);
        Limitador(txtCelular, 15);
        Limitador(txtCorreo, 200);
    }
    
    void Limitador(JTextField objeto,int limite) //limita los caracteres y su tamañao de los txt
    {
        RestrictedTextField obj = new RestrictedTextField (objeto); //elemento al cual voy a limitar
        obj.setLimit(limite); //limite de caracteres
    }
   
     void CargarDepar()
    {
        int codigoDepar=0;
        cbDepar.removeAllItems();
        for(int i=0;i<u.getTamaño();i++)
        {
            if(codigoDepar!=u.obtener(i).getCodigoDepar_Depar())
            {
                cbDepar.addItem(u.obtener(i).getDepar().toUpperCase());
                codigoDepar=u.obtener(i).getCodigoDepar_Depar();
            }
                
        }
        cbDepar.setSelectedIndex(-1);
    }
     String obtenerDepar()
    {
        if(String.valueOf(cbDepar.getSelectedItem()).equals("null"))
        {
            return "-";
        } else return String.valueOf(cbDepar.getSelectedItem()).toUpperCase();
    }
    String obtenerProvin()
    {
        if(String.valueOf(cbProvin.getSelectedItem()).equals("null"))
        {
            return "-";
        } else return String.valueOf(cbProvin.getSelectedItem()).toUpperCase();
    }
    String obtenerDistrito()
    {
        if(String.valueOf(cbDistrito.getSelectedItem()).equals("null"))
        {
            return "-";
        } else return String.valueOf(cbDistrito.getSelectedItem()).toUpperCase();
    }
    String ObtenerZona()
    {
       if(txtZona.getText().equals("")) return "-";
        else return txtZona.getText().toUpperCase();
    }
    String ObtenerVia()
    {
       if(txtVia.getText().equals("")) return "-";
        else return txtVia.getText().toUpperCase();
    }
    String ObtenerManzana()
    {
       if(txtMz.getText().equals("")) return "-";
        else return txtMz.getText().toUpperCase();
    }
    String ObtenerLote()
    {
       if(txtLote.getText().equals("")) return "-";
        else return txtLote.getText().toUpperCase();
    }
    int ObtenerNumero()
    {
       if(txtNumero.getText().equals("")) return 0;
        else return Integer.parseInt(txtNumero.getText());
    }
    String ObtenerNombre()
    {
        if(txtNombreCli.getText().equals("")) return "-";
        else return txtNombreCli.getText().toUpperCase();
    }
    String ObtenerDni()
    {
       if(txtDniCli.getText().equals("")) return "-";
        else return txtDniCli.getText();
    }
    String ObtenerSexo()
    {
        if(rbFemCli.isSelected())
        {
            return "Femenino";
        }
        else
        {
            return "Masculino";
        }
    }
    int ObtenerDiaCliente()
    {
        return dataFechaCli.getCalendar().get(Calendar.DAY_OF_MONTH);
    }
    int ObtenerMesCliente()
    {
        return dataFechaCli.getCalendar().get(Calendar.MONTH)+1;
    }
    int ObtenerAnioCliente()
    {
        return dataFechaCli.getCalendar().get(Calendar.YEAR);
    }
    
    
    //Del Laboral
    String ObtenerComercial()
    {
      if(txtComercial.getText().equals("")) return "-";
        else  return txtComercial.getText().toUpperCase();
    }
    String ObtenerActividad()
    {
       if(txtActividad.getText().equals("")) return "-";
        else return txtActividad.getText().toUpperCase();
    }
    String ObtenerOficio()
    {
       if(txtOficio.getText().equals("")) return "-";
        else return txtOficio.getText().toUpperCase();
    }
    String ObtenerTelefono()
    {
       if(txtTelefono.getText().equals("")) return "-";
        else return txtTelefono.getText();
    }
    String ObtenerCelular()
    {
       if(txtCelular.getText().equals("")) return "-";
        else return txtCelular.getText();
    }
    String ObtenerCorreo()
    {
       if(txtCorreo.getText().equals("")) return "-";
        else return txtCorreo.getText().toUpperCase();
    }
    void Modificador(){
        String dni=Registro.unregistro.getUsuario().getDNI();
        Registro e=a.buscar(dni);
        Direccion unDomicilio = new Direccion(obtenerDepar(), obtenerProvin(), obtenerDistrito(), ObtenerZona(), ObtenerVia(), ObtenerManzana(), ObtenerLote(),ObtenerNumero());
        Fecha unaFecha = new Fecha(ObtenerDiaCliente(), ObtenerMesCliente(), ObtenerAnioCliente());
        Usuario unUsuario = new Usuario(unDomicilio, ObtenerNombre(), ObtenerDni(), ObtenerSexo(), unaFecha);
        DatosLaborales unLabor = new DatosLaborales(ObtenerComercial(), ObtenerActividad(), ObtenerOficio(), ObtenerTelefono(), ObtenerCelular(), ObtenerCorreo());
        unUsuario.setFechaNacimiento(unaFecha);
        unUsuario.setDomicilio(unDomicilio);
        Registro.unregistro.setUsuario(unUsuario); //esta es una variable temporal que se le asigna valores al iniciar sesión y lo uso para mostrar datos específicos
        Registro.unregistro.setLoborales(unLabor);
        e.setUsuario(unUsuario);
        e.setLoborales(unLabor);
        a.grabar();
       
    }
    void Llenado (JTextField objeto) //limpia los txt que contienen "-"
    {
        if(objeto.getText().equals("-"))
        {
            objeto.setText("");
        }
    }
    
    private void btnModi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModi1ActionPerformed
        // TODO add your handling code here:
        txtDniCli.setEnabled(true);
        txtDniCli.setEditable(false);
        txtNombreCli.setEnabled(true);
        Llenado(txtNombreCli);
        rbFemCli.setEnabled(true);
        rbMasCli.setEnabled(true);
        dataFechaCli.setEnabled(true);
        btnG1.setVisible(true);
        btnModi1.setVisible(false);
    }//GEN-LAST:event_btnModi1ActionPerformed

    private void btnModi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModi2ActionPerformed
        // TODO add your handling code here:
        txtNumero.setEnabled(true);
        Llenado(txtNumero);
        cbProvin.setEnabled(true);
        txtZona.setEnabled(true);
        Llenado(txtZona);
        txtVia.setEnabled(true);
        Llenado(txtVia);
        txtLote.setEnabled(true);
        Llenado(txtLote);
        txtMz.setEnabled(true);
        Llenado(txtMz);
        cbDepar.setEnabled(true);
        cbDistrito.setEnabled(true);
        btnG2.setVisible(true);
        btnModi2.setVisible(false);
    }//GEN-LAST:event_btnModi2ActionPerformed

    private void btnModi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModi3ActionPerformed
        // TODO add your handling code here:
        txtActividad.setEnabled(true); 
        Llenado(txtActividad);
        txtCelular.setEnabled(true);
        Llenado(txtCelular);
        txtComercial.setEnabled(true);
        Llenado(txtComercial);
        txtCorreo.setEnabled(true);
        Llenado(txtCorreo);
        txtOficio.setEnabled(true);
        Llenado(txtOficio);
        txtTelefono.setEnabled(true);
        Llenado(txtTelefono);
        btnG3.setVisible(true);
        btnModi3.setVisible(false);
    }//GEN-LAST:event_btnModi3ActionPerformed

    private void btnG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG1ActionPerformed
        // TODO add your handling code here:
        Modificador();
        
        ValoresIniciales();
//        btnG1.setVisible(false);
//        btnModi1.setVisible(true);
    }//GEN-LAST:event_btnG1ActionPerformed

    private void btnG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG2ActionPerformed
        // TODO add your handling code here:
        Modificador();
        ValoresIniciales();
//        btnG2.setVisible(false);
//        btnModi2.setVisible(true);
    }//GEN-LAST:event_btnG2ActionPerformed

    private void btnG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG3ActionPerformed
        // TODO add your handling code here:
        Modificador();
        ValoresIniciales();
//        btnG2.setVisible(false);
//        btnModi2.setVisible(true);
    }//GEN-LAST:event_btnG3ActionPerformed

    private void cbDeparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDeparMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDeparMouseClicked

    private void cbDeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeparActionPerformed
        // TODO add your handling code here:
        int codigoProvin=0;
        cbProvin.removeAllItems();
        for(int i=0;i<u.getTamaño();i++)
        {
            if(obtenerDepar().equals(u.obtener(i).getDepar().toUpperCase())&&codigoProvin!=u.obtener(i).getCodigoProvi_Provi())
            {
                cbProvin.addItem(u.obtener(i).getProvi().toUpperCase());
                codigoProvin=u.obtener(i).getCodigoProvi_Provi();
            }
        }
        cbProvin.setSelectedIndex(-1);
    }//GEN-LAST:event_cbDeparActionPerformed

    private void cbProvinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProvinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProvinMouseClicked

    private void cbProvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProvinActionPerformed
        // TODO add your handling code here:
        int codigoDistri=0;
        cbDistrito.removeAllItems();
        for(int i=0;i<u.getTamaño();i++)
        {
            if(obtenerDepar().equals(u.obtener(i).getDepar().toUpperCase())&&obtenerProvin().equals(u.obtener(i).getProvi().toUpperCase())&&codigoDistri!=u.obtener(i).getCodigoDistri_Distri())
            {
                cbDistrito.addItem(u.obtener(i).getDistri().toUpperCase());
                codigoDistri=u.obtener(i).getCodigoDistri_Distri();
            }
        }
        cbDistrito.setSelectedIndex(-1);
    }//GEN-LAST:event_cbProvinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnG1;
    private javax.swing.JButton btnG2;
    private javax.swing.JButton btnG3;
    private javax.swing.JButton btnModi1;
    private javax.swing.JButton btnModi2;
    private javax.swing.JButton btnModi3;
    private javax.swing.JComboBox<String> cbDepar;
    private javax.swing.JComboBox<String> cbDistrito;
    private javax.swing.JComboBox<String> cbProvin;
    private com.toedter.calendar.JDateChooser dataFechaCli;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbFemCli;
    private javax.swing.JRadioButton rbMasCli;
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtComercial;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDniCli;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtMz;
    private javax.swing.JTextField txtNombreCli;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOficio;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtVia;
    private javax.swing.JTextField txtZona;
    // End of variables declaration//GEN-END:variables
}
