/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Archivos.ArregloRegistros;
import Administrativo.ArregloUbigeo;
import Atxy2k.CustomTextField.RestrictedTextField;
import Clases.DatosLaborales;
import Clases.Direccion;
import Clases.Fecha;
import Clases.Registro;
import Clases.Usuario;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author bryleo
 */
public class NuevoCliente extends javax.swing.JInternalFrame {
    ArregloRegistros a=new ArregloRegistros();
    ArregloUbigeo u = new ArregloUbigeo();
    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        DatosRUC.setVisible(false);
        ValoresInciales();
        Limitadores();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        genero = new javax.swing.ButtonGroup();
        gbTipos = new javax.swing.ButtonGroup();
        VentanaRegistro = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNombreCli = new javax.swing.JTextField();
        txtDniCli = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbMasCli = new javax.swing.JRadioButton();
        rbFemCli = new javax.swing.JRadioButton();
        dataFechaCli = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        txtZona = new javax.swing.JTextField();
        txtVia = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtMz = new javax.swing.JTextField();
        txtLote = new javax.swing.JTextField();
        cbDepar = new javax.swing.JComboBox<>();
        cbProvin = new javax.swing.JComboBox<>();
        cbDistrito = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        txtComercial = new javax.swing.JTextField();
        txtActividad = new javax.swing.JTextField();
        txtOficio = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        dataFechaRegistro = new com.toedter.calendar.JDateChooser();
        cbCategoria = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        DatosRUC = new javax.swing.JPanel();
        txtDniRUC = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        txtClaveRUC = new javax.swing.JTextField();
        PanelEncuesta = new javax.swing.JPanel();
        rb0 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        btnSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("NUEVO CLIENTE");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS PERSONALES"));

        txtNombreCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres Completos"));

        txtDniCli.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Género"));

        genero.add(rbMasCli);
        rbMasCli.setText("Masculino");

        genero.add(rbFemCli);
        rbFemCli.setText("Femenino");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMasCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFemCli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMasCli)
                    .addComponent(rbFemCli))
                .addContainerGap())
        );

        dataFechaCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Nacimiento"));
        dataFechaCli.setDateFormatString("dd/MM/yy");
        dataFechaCli.setMaxSelectableDate(new java.util.Date(1009778468000L));
        dataFechaCli.setMinSelectableDate(new java.util.Date(-631130332000L));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreCli)
                    .addComponent(txtDniCli)
                    .addComponent(dataFechaCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtDniCli, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataFechaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DOMICILIO"));

        txtZona.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo & Nombre de Zona"));

        txtVia.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo & Nombre de Via"));

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("N°"));

        txtMz.setBorder(javax.swing.BorderFactory.createTitledBorder("Mz"));

        txtLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Lt"));

        cbDepar.setBorder(javax.swing.BorderFactory.createTitledBorder("DEPARTAMENTO"));
        cbDepar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDeparMouseClicked(evt);
            }
        });
        cbDepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeparActionPerformed(evt);
            }
        });

        cbProvin.setBorder(javax.swing.BorderFactory.createTitledBorder("PROVINCIA"));
        cbProvin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbProvinMouseClicked(evt);
            }
        });
        cbProvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProvinActionPerformed(evt);
            }
        });

        cbDistrito.setBorder(javax.swing.BorderFactory.createTitledBorder("DISTRITO"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVia)
                    .addComponent(txtZona)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMz, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbProvin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbProvin, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(cbDepar)
                    .addComponent(cbDistrito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS LABORALES"));

        txtComercial.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Comercial"));

        txtActividad.setBorder(javax.swing.BorderFactory.createTitledBorder("Actividad Económica"));

        txtOficio.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficio"));

        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));

        txtCelular.setBorder(javax.swing.BorderFactory.createTitledBorder("Celular"));

        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComercial)
                    .addComponent(txtActividad)
                    .addComponent(txtOficio)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOficio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DEL REGISTRO"));

        dataFechaRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Registro"));
        dataFechaRegistro.setEnabled(false);

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1° Categoría", "2° Categoría", "3° Categoría", "4° Categoría", "5° Categoría" }));
        cbCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoría"));
        cbCategoria.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataFechaRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        VentanaRegistro.setViewportView(jPanel5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 315;
        gridBagConstraints.ipady = 384;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(VentanaRegistro, gridBagConstraints);

        btnGuardar.setText("GUARDAR DATOS");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 87, 18, 0);
        getContentPane().add(btnGuardar, gridBagConstraints);

        DatosRUC.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS RUC"));

        txtDniRUC.setEditable(false);
        txtDniRUC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDniRUC.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));

        txtRUC.setEditable(false);
        txtRUC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRUC.setBorder(javax.swing.BorderFactory.createTitledBorder("RUC"));

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtClaveRUC.setEditable(false);
        txtClaveRUC.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtClaveRUC.setBorder(javax.swing.BorderFactory.createTitledBorder("CLAVE SOL"));

        javax.swing.GroupLayout DatosRUCLayout = new javax.swing.GroupLayout(DatosRUC);
        DatosRUC.setLayout(DatosRUCLayout);
        DatosRUCLayout.setHorizontalGroup(
            DatosRUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosRUCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosRUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosRUCLayout.createSequentialGroup()
                        .addGroup(DatosRUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDniRUC, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(txtRUC))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtClaveRUC))
                .addContainerGap())
            .addGroup(DatosRUCLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosRUCLayout.setVerticalGroup(
            DatosRUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosRUCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDniRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClaveRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 18, 0, 0);
        getContentPane().add(DatosRUC, gridBagConstraints);

        gbTipos.add(rb0);
        rb0.setText("Presento alquiler de inmuebles");

        gbTipos.add(rb1);
        rb1.setText("Presento venta de inmuebles y/o valores mobiliarios");

        gbTipos.add(rb3);
        rb3.setText("Presento trabajo independiente - temporal o eventual");

        gbTipos.add(rb4);
        rb4.setText("Presento trabajo dependiente - permanente");

        gbTipos.add(rb2);
        rb2.setText("Presento una Empresa");

        btnSiguiente.setText("ACEPTAR");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pensar.png"))); // NOI18N

        javax.swing.GroupLayout PanelEncuestaLayout = new javax.swing.GroupLayout(PanelEncuesta);
        PanelEncuesta.setLayout(PanelEncuestaLayout);
        PanelEncuestaLayout.setHorizontalGroup(
            PanelEncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEncuestaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(PanelEncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelEncuestaLayout.createSequentialGroup()
                    .addGap(10, 22, Short.MAX_VALUE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(59, 59, 59)
                    .addGroup(PanelEncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rb0)
                        .addComponent(rb1)
                        .addComponent(rb2)
                        .addComponent(rb3)
                        .addComponent(rb4))
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        PanelEncuestaLayout.setVerticalGroup(
            PanelEncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEncuestaLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(PanelEncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelEncuestaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(PanelEncuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelEncuestaLayout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addComponent(btnSiguiente))
                        .addGroup(PanelEncuestaLayout.createSequentialGroup()
                            .addComponent(rb0)
                            .addGap(6, 6, 6)
                            .addComponent(rb1)
                            .addGap(6, 6, 6)
                            .addComponent(rb2)
                            .addGap(6, 6, 6)
                            .addComponent(rb3)
                            .addGap(6, 6, 6)
                            .addComponent(rb4)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 163;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 18, 0);
        getContentPane().add(PanelEncuesta, gridBagConstraints);

        setBounds(0, 0, 872, 492);
    }// </editor-fold>//GEN-END:initComponents

    void Limitadores()
    {
        LimitadorText(txtNombreCli, 200);
        LimitadorNum(txtDniCli,8);
        
        LimitadorText(txtZona, 200);
        LimitadorText(txtVia, 200);
        LimitadorAlfanum(txtMz, 4);
        LimitadorAlfanum(txtLote, 4);
        LimitadorNum(txtNumero, 6);
        LimitadorText(txtComercial, 250);
        LimitadorText(txtActividad, 250);
        LimitadorText(txtOficio, 250);
        LimitadorNum(txtTelefono, 15);
        LimitadorNum(txtCelular, 15);
        LimitadorCorreo(txtCorreo, 200);
    }
    
    void LimitadorNum(JTextField objeto,int limite) //limita los caracteres y su tamañao de los txt
    {
        RestrictedTextField obj = new RestrictedTextField (objeto); //elemento al cual voy a limitar
        obj.setLimit(limite); //limite de caracteres
        
        obj.setOnlyNums(true);//para que solo acepte números
        //obj.setOnlyText(true);//para que solo me acepte letras
    }
    void LimitadorText(JTextField objeto,int limite) //limita los caracteres y su tamañao de los txt
    {
        RestrictedTextField obj = new RestrictedTextField (objeto); //elemento al cual voy a limitar
        obj.setLimit(limite); //limite de caracteres
        //obj.setOnlyNums(true);//para que solo acepte números
        obj.setOnlyText(true);//para que solo me acepte letras
        obj.setAcceptSpace(true); //acepta espacios
    }
    void LimitadorAlfanum(JTextField objeto,int limite) //limita los caracteres y su tamañao de los txt
    {
        RestrictedTextField obj = new RestrictedTextField (objeto); //elemento al cual voy a limitar
        obj.setLimit(limite); //limite de caracteres
        obj.setOnlyAlphaNumeric(true);
    }
    void LimitadorCorreo(JTextField objeto,int limite)
    {
        RestrictedTextField obj = new RestrictedTextField (objeto); //elemento al cual voy a limitar
        obj.setLimit(limite); //limite de caracteres
        obj.setAcceptCharacters(".0123456789abcdefghijklmnñopqrstuvwxyz-_@");
        obj.setOnlyCustomCharacters(true);
        
    }
    //del Usuario
    
    String ObtenerZona()
    {
       if(txtZona.getText().equals("")) return "-";
        else return txtZona.getText().toUpperCase();
    }
    String ObtenerVia()
    {
       if(txtVia.getText().equals("")) return "-";
        else return txtVia.getText().toUpperCase();
    }
    String ObtenerManzana()
    {
       if(txtMz.getText().equals("")) return "-";
        else return txtMz.getText().toUpperCase();
    }
    String ObtenerLote()
    {
       if(txtLote.getText().equals("")) return "-";
        else return txtLote.getText().toUpperCase();
    }
    int ObtenerNumero()
    {
       if(txtNumero.getText().equals("")) return 0;
        else return Integer.parseInt(txtNumero.getText());
    }
    String ObtenerNombre()
    {
        if(txtNombreCli.getText().equals("")) return "-";
        else return txtNombreCli.getText().toUpperCase();
    }
    String ObtenerDni()
    {
       if(txtDniCli.getText().equals("")) return "-";
        else return txtDniCli.getText();
    }
    String ObtenerSexo()
    {
        if(rbFemCli.isSelected())
        {
            return "Femenino";
        }
        else
        {
            return "Masculino";
        }
    }
    int ObtenerDiaCliente()
    {
        return dataFechaCli.getCalendar().get(Calendar.DAY_OF_MONTH);
    }
    int ObtenerMesCliente()
    {
        return dataFechaCli.getCalendar().get(Calendar.MONTH)+1;
    }
    int ObtenerAnioCliente()
    {
        return dataFechaCli.getCalendar().get(Calendar.YEAR);
    }
    
    //Del Registro
    int ObtenerDiaRegistro()
    {
        return dataFechaRegistro.getCalendar().get(Calendar.DAY_OF_MONTH);
    }
    int ObtenerMesRegistro()
    {
        return dataFechaRegistro.getCalendar().get(Calendar.MONTH)+1;
    }
    int ObtenerAnioRegistro()
    {
        return dataFechaRegistro.getCalendar().get(Calendar.YEAR);
    }  
    int ObtenerCategoria()
    {
        return cbCategoria.getSelectedIndex();
    }
    
    //Del Laboral
    String ObtenerComercial()
    {
      if(txtComercial.getText().equals("")) return "-";
        else  return txtComercial.getText().toUpperCase();
    }
    String ObtenerActividad()
    {
       if(txtActividad.getText().equals("")) return "-";
        else return txtActividad.getText().toUpperCase();
    }
    String ObtenerOficio()
    {
       if(txtOficio.getText().equals("")) return "-";
        else return txtOficio.getText().toUpperCase();
    }
    String ObtenerTelefono()
    {
       if(txtTelefono.getText().equals("")) return "-";
        else return txtTelefono.getText();
    }
    String ObtenerCelular()
    {
       if(txtCelular.getText().equals("")) return "-";
        else return txtCelular.getText();
    }
    String ObtenerCorreo()
    {
       if(txtCorreo.getText().equals("")) return "-";
        else return txtCorreo.getText().toUpperCase();
    }
    int ObtenerCategoriaTipo ()
    {
        if(rb0.isSelected())return 0;
        else if (rb1.isSelected()) return 1;
        else if (rb2.isSelected()) return 2;
        else if (rb3.isSelected()) return 3;
        else return 4;
    }
     void CargarDepar()
    {
        int codigoDepar=0;
        cbDepar.removeAllItems();
        for(int i=0;i<u.getTamaño();i++)
        {
            if(codigoDepar!=u.obtener(i).getCodigoDepar_Depar())
            {
                cbDepar.addItem(u.obtener(i).getDepar().toUpperCase());
                codigoDepar=u.obtener(i).getCodigoDepar_Depar();
            }
                
        }
        cbDepar.setSelectedIndex(-1);
    }
    String obtenerDepar()
    {
        if(String.valueOf(cbDepar.getSelectedItem()).equals("null"))
        {
            return "-";
        } else return String.valueOf(cbDepar.getSelectedItem()).toUpperCase();
    }
    String obtenerProvin()
    {
        if(String.valueOf(cbProvin.getSelectedItem()).equals("null"))
        {
            return "-";
        } else return String.valueOf(cbProvin.getSelectedItem()).toUpperCase();
    }
    String obtenerDistrito()
    {
        if(String.valueOf(cbDistrito.getSelectedItem()).equals("null"))
        {
            return "-";
        } else return String.valueOf(cbDistrito.getSelectedItem()).toUpperCase();
    }
    
    void ValoresInciales()
    {
        rbMasCli.setSelected(true);
        Date nacimiento = new Date ();
        nacimiento.setDate(31);
        nacimiento.setMonth(11);
        nacimiento.setYear(2001);
        dataFechaCli.setDate(nacimiento);
        rb0.setSelected(true);
        CargarDepar();
        dataFechaRegistro.setDate(fecha);
        VentanaRegistro.setVisible(false);
        btnGuardar.setVisible(false);
        
    }
    Date fecha = new Date();
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(obtenerDepar().equals("-")||obtenerDistrito().equals("-")||obtenerProvin().equals("-")||ObtenerDni().equals("-")||ObtenerNombre().equals("-"))
        {
            JOptionPane.showMessageDialog(null,"Para guardar un usuario, es necesario que NOMBRE, DNI, DEPARTAMENTO, PROVINCIA & DISTRITO contengan datos validos");
        }
        else
        {
            Registro x=a.buscar(ObtenerDni());

            if (x==null){//Si no encontramos DNI repetido ingresa al if

                Direccion unDomicilio = new Direccion(obtenerDepar(), obtenerProvin(),obtenerDistrito(),ObtenerZona(),ObtenerVia(), ObtenerManzana(),ObtenerLote(),ObtenerNumero());
                Fecha unaFecha = new Fecha(ObtenerDiaCliente(),ObtenerMesCliente(),ObtenerAnioCliente());
                Usuario unUsuario = new Usuario(unDomicilio,ObtenerNombre(),ObtenerDni(),ObtenerSexo(), unaFecha);
                DatosLaborales unLabor = new DatosLaborales(ObtenerComercial(),ObtenerActividad(),ObtenerOficio(),ObtenerTelefono(),ObtenerCelular(),ObtenerCorreo());
                Fecha unaFechaRegistro = new Fecha(ObtenerDiaRegistro(),ObtenerMesRegistro(),ObtenerAnioRegistro());
                x=new Registro(unUsuario,ObtenerCategoria(),unaFechaRegistro,unLabor);

                //Asosiación

                unUsuario.setFechaNacimiento(unaFecha);
                unUsuario.setDomicilio(unDomicilio);

                x.setFechaRegistro(unaFechaRegistro);
                x.setLoborales(unLabor);
                x.setUsuario(unUsuario);

                a.adicionar(x);
                a.grabar();

                 //mostreo de datos
                JOptionPane.showMessageDialog(null, "Por favor recordar su cambio posteriormente", "CLAVE SOL GENERADA",1);
                txtRUC.setText(x.getRUC());
                txtClaveRUC.setText(x.getClaveSOL());
                txtDniRUC.setText(x.getUsuario().getDNI());

                //ocultar comandos
                VentanaRegistro.setVisible(false);

                btnGuardar.setVisible(false);
                DatosRUC.setVisible(true);
            }else JOptionPane.showMessageDialog(this,"DNI ya Registrado");
        }
   
 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.dispose(); //cierra solo la ventana NuevoCliente
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "Categoría tributaria asignada\nPara realizar el cambio de este, porfavor acercarse a una de nuestras oficinas");
        PanelEncuesta.setVisible(false);
        
        VentanaRegistro.setVisible(true);
        btnGuardar.setVisible(true);
        
        
        cbCategoria.setSelectedIndex(ObtenerCategoriaTipo());
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void cbDeparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDeparMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbDeparMouseClicked

    private void cbDeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeparActionPerformed
        // TODO add your handling code here:
        int codigoProvin=0;
        cbProvin.removeAllItems();
        for(int i=0;i<u.getTamaño();i++)
        {
            if(obtenerDepar().equals(u.obtener(i).getDepar().toUpperCase())&&codigoProvin!=u.obtener(i).getCodigoProvi_Provi())
            {
                cbProvin.addItem(u.obtener(i).getProvi().toUpperCase());
                codigoProvin=u.obtener(i).getCodigoProvi_Provi();
            }
        }
        cbProvin.setSelectedIndex(-1);
    }//GEN-LAST:event_cbDeparActionPerformed

    private void cbProvinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProvinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProvinMouseClicked

    private void cbProvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProvinActionPerformed
        // TODO add your handling code here:
        int codigoDistri=0;
        cbDistrito.removeAllItems();
        for(int i=0;i<u.getTamaño();i++)
        {
            if(obtenerDepar().equals(u.obtener(i).getDepar().toUpperCase())&&obtenerProvin().equals(u.obtener(i).getProvi().toUpperCase())&&codigoDistri!=u.obtener(i).getCodigoDistri_Distri())
            {
                cbDistrito.addItem(u.obtener(i).getDistri().toUpperCase());
                codigoDistri=u.obtener(i).getCodigoDistri_Distri();
            }
        }
        cbDistrito.setSelectedIndex(-1);
    }//GEN-LAST:event_cbProvinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosRUC;
    private javax.swing.JPanel PanelEncuesta;
    private javax.swing.JScrollPane VentanaRegistro;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbDepar;
    private javax.swing.JComboBox<String> cbDistrito;
    private javax.swing.JComboBox<String> cbProvin;
    private com.toedter.calendar.JDateChooser dataFechaCli;
    private com.toedter.calendar.JDateChooser dataFechaRegistro;
    private javax.swing.ButtonGroup gbTipos;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rb0;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rbFemCli;
    private javax.swing.JRadioButton rbMasCli;
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtClaveRUC;
    private javax.swing.JTextField txtComercial;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDniCli;
    private javax.swing.JTextField txtDniRUC;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtMz;
    private javax.swing.JTextField txtNombreCli;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOficio;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtVia;
    private javax.swing.JTextField txtZona;
    // End of variables declaration//GEN-END:variables
}
