/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Archivos.Arreglo1Tributo;
import Atxy2k.CustomTextField.RestrictedTextField;

import Clases.Fecha;
import Clases.PrimeraCategoria;
import Clases.Registro;
import Clases.Tributo;
import Clases.Usuario;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

import javax.swing.JTextField;

/**
 *
 * @author bryleo
 */
public class Pri_Categor extends javax.swing.JInternalFrame {
    Arreglo1Tributo a=new Arreglo1Tributo();
    /**
     * Creates new form Pri_Categor
     */
    public Pri_Categor() {
        initComponents();
        ValoresIniciales();
        LimitadorNum(txtValor,20);
    }
    void LimitadorNum(JTextField objeto,int limite) //limita los caracteres y su tamañao de los txt
    {
        RestrictedTextField obj = new RestrictedTextField (objeto); //elemento al cual voy a limitar
        obj.setLimit(limite); //limite de caracteres
       
        obj.setAcceptCharacters(".0123456789");
        obj.setOnlyCustomCharacters(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelMostrar1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbDni1 = new javax.swing.JLabel();
        lbNombre1 = new javax.swing.JLabel();
        lbEdad1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        dataEmision1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        lbImpuesto = new javax.swing.JLabel();
        lbImpuesto1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        PanelReseccion1 = new javax.swing.JScrollPane();
        PanelR = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtValor = new javax.swing.JTextField();
        lbReten = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbDni = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbEdad = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        dataEmision = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PRIMERA CATEGORÍA");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS PERSONALES"));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        lbDni1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dni"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 20);
        jPanel7.add(lbDni1, gridBagConstraints);

        lbNombre1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 20);
        jPanel7.add(lbNombre1, gridBagConstraints);

        lbEdad1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 20);
        jPanel7.add(lbEdad1, gridBagConstraints);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO"));

        dataEmision1.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dataEmision1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(dataEmision1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 13, Short.MAX_VALUE)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS TRIBUTARIOS"));
        jPanel1.setLayout(null);

        lbImpuesto.setBorder(javax.swing.BorderFactory.createTitledBorder("Impuesto Mensual:"));
        jPanel1.add(lbImpuesto);
        lbImpuesto.setBounds(20, 110, 278, 60);

        lbImpuesto1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad ganada por arrendamiento"));
        jPanel1.add(lbImpuesto1);
        lbImpuesto1.setBounds(20, 30, 278, 60);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMostrar1Layout = new javax.swing.GroupLayout(PanelMostrar1);
        PanelMostrar1.setLayout(PanelMostrar1Layout);
        PanelMostrar1Layout.setHorizontalGroup(
            PanelMostrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMostrar1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelMostrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelMostrar1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(PanelMostrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PanelMostrar1Layout.setVerticalGroup(
            PanelMostrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMostrar1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelMostrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMostrar1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMostrar1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 85;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        getContentPane().add(PanelMostrar1, gridBagConstraints);

        PanelR.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS TRIBUTARIOS"));
        jPanel2.setLayout(null);

        txtValor.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad Ganada por arrendamiento"));
        jPanel2.add(txtValor);
        txtValor.setBounds(20, 30, 280, 60);

        lbReten.setBorder(javax.swing.BorderFactory.createTitledBorder("IMPUESTO"));
        jPanel2.add(lbReten);
        lbReten.setBounds(20, 100, 280, 70);

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(60, 190, 77, 32);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar);
        btnGuardar.setBounds(170, 190, 77, 32);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 319;
        gridBagConstraints.ipady = 249;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 6, 0);
        PanelR.add(jPanel2, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS PERSONALES"));
        jPanel5.setLayout(null);

        lbDni.setBorder(javax.swing.BorderFactory.createTitledBorder("Dni"));
        jPanel5.add(lbDni);
        lbDni.setBounds(10, 170, 200, 60);

        lbNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        jPanel5.add(lbNombre);
        lbNombre.setBounds(10, 30, 200, 60);

        lbEdad.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));
        jPanel5.add(lbEdad);
        lbEdad.setBounds(10, 100, 200, 60);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 229;
        gridBagConstraints.ipady = 249;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 6, 0);
        PanelR.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DEL REGISTRO"));
        jPanel6.setLayout(null);

        dataEmision.setEnabled(false);
        jPanel6.add(dataEmision);
        dataEmision.setBounds(20, 30, 190, 29);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 229;
        gridBagConstraints.ipady = 89;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        PanelR.add(jPanel6, gridBagConstraints);

        PanelReseccion1.setViewportView(PanelR);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 414;
        gridBagConstraints.ipady = 421;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        getContentPane().add(PanelReseccion1, gridBagConstraints);

        setBounds(0, 0, 1042, 475);
    }// </editor-fold>//GEN-END:initComponents
    Date fecha = new Date();
    void ValoresIniciales()
    {
        PanelMostrar1.setVisible(false);
        PanelReseccion1.setVisible(true);
        dataEmision.setDate(fecha);
        btnGuardar.setVisible(false);
        lbNombre.setText(Registro.unregistro.getUsuario().getNombre());
        lbEdad.setText(String.valueOf(Registro.unregistro.getUsuario().getEdad()));
        lbDni.setText(Registro.unregistro.getUsuario().getDNI());
    }
    void MostrarValores() //del panel mostrar datos
    {
        lbNombre1.setText(Registro.unregistro.getUsuario().getNombre());
        lbEdad1.setText(String.valueOf(Registro.unregistro.getUsuario().getEdad()));
        lbDni1.setText(Registro.unregistro.getUsuario().getDNI());
        dataEmision1.setDate(fecha);
    }
    
    double ObtenerCantidad()
    {
        return Double.parseDouble(txtValor.getText());
    }
    int ObtenerDia()
    {
        return dataEmision.getCalendar().get(Calendar.DAY_OF_MONTH);
    }
    int ObtenerMes()
    {
        return dataEmision.getCalendar().get(Calendar.MONTH)+1;
    }
    int ObtenerAnio()
    {
        return dataEmision.getCalendar().get(Calendar.YEAR);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(txtValor.getText().equals("")){
            JOptionPane.showMessageDialog(null,"No ha ingresado la Cantidad ganada por arrendamiento");
        }else{
            
        PrimeraCategoria unacategoria = new PrimeraCategoria(ObtenerCantidad());
        lbReten.setText(String.valueOf(unacategoria.getImpuestoMensual()));
        
        
        btnGuardar.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
         if(txtValor.getText().equals("")){
            JOptionPane.showMessageDialog(null,"No ha ingresado la Cantidad ganada por arrendamiento");
        }else{
             PrimeraCategoria categoria1 = new PrimeraCategoria(ObtenerCantidad());
             if(categoria1.getImpuestoMensual()==Double.parseDouble(lbReten.getText())){     
                MostrarValores();
                Usuario unUsuario = new Usuario(Registro.unregistro.getUsuario().getNombre(), Registro.unregistro.getUsuario().getDNI());
                Fecha unaFechaEmi = new Fecha(ObtenerDia(), ObtenerMes(), ObtenerAnio());
                Tributo x = new Tributo(unUsuario, unaFechaEmi);
                x.setContribuyente(unUsuario);
                x.setFechaEmision(unaFechaEmi);
                x.setCategoria1(categoria1);
                a.adicionar(x);
                a.grabar();

                lbImpuesto1.setText(String.valueOf(x.getCategoria1().getRenta()));
                lbImpuesto.setText(String.valueOf(x.getCategoria1().getImpuestoMensual()));

                PanelReseccion1.setVisible(false);
                PanelMostrar1.setVisible(true);
             }else{
                 JOptionPane.showMessageDialog(null,"Ha modificado el valor ingresado anteriormente");
             }
         }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMostrar1;
    private javax.swing.JPanel PanelR;
    private javax.swing.JScrollPane PanelReseccion1;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dataEmision;
    private com.toedter.calendar.JDateChooser dataEmision1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbDni;
    private javax.swing.JLabel lbDni1;
    private javax.swing.JLabel lbEdad;
    private javax.swing.JLabel lbEdad1;
    private javax.swing.JLabel lbImpuesto;
    private javax.swing.JLabel lbImpuesto1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JLabel lbReten;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
