/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Archivos.Arreglo3Tributo;
import Atxy2k.CustomTextField.RestrictedTextField;
import Clases.Fecha;
import Clases.Registro;
import Clases.TerceraCategoria;
import Clases.Tributo;
import Clases.Usuario;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author bryleo
 */
public class Ter_Categor extends javax.swing.JInternalFrame {

    Arreglo3Tributo a=new Arreglo3Tributo();
    /**
     * Creates new form Ter_Categor
     */
    public Ter_Categor() {
        initComponents();
        ValoresIniciales();
        Limitadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelReseccion3 = new javax.swing.JScrollPane();
        PanelR = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtperdidas = new javax.swing.JTextField();
        txtcreditos = new javax.swing.JTextField();
        txtingresob = new javax.swing.JTextField();
        txtcostoc = new javax.swing.JTextField();
        txtGastos = new javax.swing.JTextField();
        txtadicionales = new javax.swing.JTextField();
        txtotrosingresos = new javax.swing.JTextField();
        txtdeducciones = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cbPersona = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbRetencion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbDni = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbEdad = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        dataEmision = new com.toedter.calendar.JDateChooser();
        PanelMostrar3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbrenta = new javax.swing.JLabel();
        lbadicionales = new javax.swing.JLabel();
        lbcostoC = new javax.swing.JLabel();
        lbingresoB = new javax.swing.JLabel();
        lbImpuesto = new javax.swing.JLabel();
        lbRentaB = new javax.swing.JLabel();
        lbperdida = new javax.swing.JLabel();
        lbgastos = new javax.swing.JLabel();
        lbdeducciones = new javax.swing.JLabel();
        lbotros = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbDni1 = new javax.swing.JLabel();
        lbNombre1 = new javax.swing.JLabel();
        lbEdad1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        dataEmision1 = new com.toedter.calendar.JDateChooser();
        btnAceptar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TERCERA CATEGORÍA");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PanelR.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS TRIBUTARIOS"));
        jPanel2.setLayout(null);

        txtperdidas.setBorder(javax.swing.BorderFactory.createTitledBorder("PERDIDAS TRIBUTARIAS COMPENSABLES"));
        jPanel2.add(txtperdidas);
        txtperdidas.setBounds(10, 230, 230, 60);

        txtcreditos.setBorder(javax.swing.BorderFactory.createTitledBorder("CREDITOS COMPENSABLES"));
        jPanel2.add(txtcreditos);
        txtcreditos.setBounds(260, 230, 220, 60);

        txtingresob.setBorder(javax.swing.BorderFactory.createTitledBorder("INGRESO BRUTO"));
        jPanel2.add(txtingresob);
        txtingresob.setBounds(10, 90, 140, 60);

        txtcostoc.setBorder(javax.swing.BorderFactory.createTitledBorder("COSTO COMPUTABLE"));
        txtcostoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostocActionPerformed(evt);
            }
        });
        jPanel2.add(txtcostoc);
        txtcostoc.setBounds(170, 90, 150, 60);

        txtGastos.setBorder(javax.swing.BorderFactory.createTitledBorder("GASTOS"));
        jPanel2.add(txtGastos);
        txtGastos.setBounds(330, 90, 150, 60);

        txtadicionales.setBorder(javax.swing.BorderFactory.createTitledBorder("ADICIONALES"));
        jPanel2.add(txtadicionales);
        txtadicionales.setBounds(170, 160, 150, 60);

        txtotrosingresos.setBorder(javax.swing.BorderFactory.createTitledBorder("OTROS INGRESOS"));
        jPanel2.add(txtotrosingresos);
        txtotrosingresos.setBounds(10, 160, 140, 60);

        txtdeducciones.setBorder(javax.swing.BorderFactory.createTitledBorder("DEDUCCIONES"));
        jPanel2.add(txtdeducciones);
        txtdeducciones.setBounds(330, 160, 150, 60);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar);
        btnGuardar.setBounds(380, 320, 77, 32);

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(270, 320, 77, 32);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 70, 480, 10);

        cbPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jurídica", "No Jurídica" }));
        jPanel2.add(cbPersona);
        cbPersona.setBounds(320, 30, 130, 30);

        jLabel1.setText("Tipo de Persona que realiza el trámite tributario:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 280, 16);

        lbRetencion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbRetencion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRetencion.setBorder(javax.swing.BorderFactory.createTitledBorder("IMPUESTO"));
        jPanel2.add(lbRetencion);
        lbRetencion.setBounds(10, 300, 220, 70);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 499;
        gridBagConstraints.ipady = 383;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 12, 0);
        PanelR.add(jPanel2, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS PERSONALES"));
        jPanel5.setLayout(null);

        lbDni.setBorder(javax.swing.BorderFactory.createTitledBorder("Dni"));
        jPanel5.add(lbDni);
        lbDni.setBounds(10, 170, 200, 60);

        lbNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        jPanel5.add(lbNombre);
        lbNombre.setBounds(10, 30, 200, 60);

        lbEdad.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));
        jPanel5.add(lbEdad);
        lbEdad.setBounds(10, 100, 200, 60);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 229;
        gridBagConstraints.ipady = 249;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 25);
        PanelR.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DEL REGISTRO"));
        jPanel6.setLayout(null);

        dataEmision.setEnabled(false);
        jPanel6.add(dataEmision);
        dataEmision.setBounds(20, 30, 190, 29);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 229;
        gridBagConstraints.ipady = 89;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 18, 12, 25);
        PanelR.add(jPanel6, gridBagConstraints);

        PanelReseccion3.setViewportView(PanelR);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 320;
        gridBagConstraints.ipady = 564;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        getContentPane().add(PanelReseccion3, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS TRIBUTARIOS"));
        jPanel1.setLayout(null);

        lbrenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Renta neta:"));
        jPanel1.add(lbrenta);
        lbrenta.setBounds(170, 240, 127, 60);

        lbadicionales.setBorder(javax.swing.BorderFactory.createTitledBorder("Adiciones:"));
        jPanel1.add(lbadicionales);
        lbadicionales.setBounds(160, 170, 140, 60);

        lbcostoC.setBorder(javax.swing.BorderFactory.createTitledBorder("Costo Computable:"));
        jPanel1.add(lbcostoC);
        lbcostoC.setBounds(20, 100, 130, 60);

        lbingresoB.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso Bruto: "));
        jPanel1.add(lbingresoB);
        lbingresoB.setBounds(20, 30, 278, 60);

        lbImpuesto.setBorder(javax.swing.BorderFactory.createTitledBorder("Impuesto:"));
        jPanel1.add(lbImpuesto);
        lbImpuesto.setBounds(20, 480, 278, 70);

        lbRentaB.setBorder(javax.swing.BorderFactory.createTitledBorder("Renta bruta:"));
        jPanel1.add(lbRentaB);
        lbRentaB.setBounds(20, 320, 280, 60);

        lbperdida.setBorder(javax.swing.BorderFactory.createTitledBorder("Perdidas Tributarias Compensables:"));
        jPanel1.add(lbperdida);
        lbperdida.setBounds(20, 390, 278, 80);

        lbgastos.setBorder(javax.swing.BorderFactory.createTitledBorder("Gastos:"));
        jPanel1.add(lbgastos);
        lbgastos.setBounds(160, 100, 140, 60);

        lbdeducciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Deducciones:"));
        jPanel1.add(lbdeducciones);
        lbdeducciones.setBounds(20, 240, 130, 60);

        lbotros.setBorder(javax.swing.BorderFactory.createTitledBorder("Otros Ingresos:"));
        jPanel1.add(lbotros);
        lbotros.setBounds(20, 170, 130, 60);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS PERSONALES"));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        lbDni1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dni"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 20);
        jPanel7.add(lbDni1, gridBagConstraints);

        lbNombre1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 20);
        jPanel7.add(lbNombre1, gridBagConstraints);

        lbEdad1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 20);
        jPanel7.add(lbEdad1, gridBagConstraints);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO"));

        dataEmision1.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dataEmision1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(dataEmision1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMostrar3Layout = new javax.swing.GroupLayout(PanelMostrar3);
        PanelMostrar3.setLayout(PanelMostrar3Layout);
        PanelMostrar3Layout.setHorizontalGroup(
            PanelMostrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMostrar3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(PanelMostrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelMostrar3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        PanelMostrar3Layout.setVerticalGroup(
            PanelMostrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMostrar3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(PanelMostrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelMostrar3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(PanelMostrar3, gridBagConstraints);

        setBounds(0, 0, 950, 606);
    }// </editor-fold>//GEN-END:initComponents
    void Limitadores(){
        LimitadorNum(txtingresob,20);
        LimitadorNum(txtcostoc,20);
        LimitadorNum(txtGastos,20);
        LimitadorNum(txtotrosingresos,20);
        LimitadorNum(txtadicionales,20);
        LimitadorNum(txtdeducciones, 20);
        LimitadorNum(txtperdidas,20);
        LimitadorNum(txtcreditos,20);
    }
    void LimitadorNum(JTextField objeto,int limite) //limita los caracteres y su tamañao de los txt
    {
        RestrictedTextField obj = new RestrictedTextField (objeto); //elemento al cual voy a limitar
        obj.setLimit(limite);
         obj.setAcceptCharacters(".0123456789");//limita los caracteres a numeros y el punto para el ingreso de datos decimales
        obj.setOnlyCustomCharacters(true);
    }
    Date calendario=new Date();
    void ValoresIniciales()
    {
        PanelMostrar3.setVisible(false);
        PanelReseccion3.setVisible(true);
        btnGuardar.setVisible(false);
        cbPersona.setSelectedIndex(-1);
        //calendario;
        dataEmision.setDate(calendario);
        lbNombre.setText(Registro.unregistro.getUsuario().getNombre());
        lbEdad.setText(String.valueOf(Registro.unregistro.getUsuario().getEdad()));
        lbDni.setText(Registro.unregistro.getUsuario().getDNI());
    }
    void MostrarValores()
    {
        lbNombre1.setText(Registro.unregistro.getUsuario().getNombre());
        lbEdad1.setText(String.valueOf(Registro.unregistro.getUsuario().getEdad()));
        lbDni1.setText(Registro.unregistro.getUsuario().getDNI());
        dataEmision1.setDate(calendario);
    }
    int obtenerPersona()
    {
        return cbPersona.getSelectedIndex();
    }
    double obtenerIngresoB()
    {
        return Double.parseDouble(txtingresob.getText());
    }
    double obtenerCostoC()
    {
        return Double.parseDouble(txtcostoc.getText());
    }
    double obtenerGastos()
    {
        return Double.parseDouble(txtGastos.getText());
    }
    double obtenerOtros()
    {
        return Double.parseDouble(txtotrosingresos.getText());
    }
    double obtenerAdicionales()
    {
        return Double.parseDouble(txtadicionales.getText());
    }
    double obtenerDeducciones()
    {
        return Double.parseDouble(txtdeducciones.getText());
    }
    double obtenerPerdidas()
    {
        return Double.parseDouble(txtperdidas.getText());
    }
    double obtenerCreditos()
    {
        return Double.parseDouble(txtcreditos.getText());
    }
    
    int ObtenerDia()
    {
        return dataEmision.getCalendar().get(Calendar.DAY_OF_MONTH);
    }
    int ObtenerMes()
    {
        return dataEmision.getCalendar().get(Calendar.MONTH)+1;
    }
    int ObtenerAnio()
    {
        return dataEmision.getCalendar().get(Calendar.YEAR);
    }
    String Validar(){
        if(txtingresob.getText().equals("")){
            return "Ingreso Bruto (Vacio)";
        }else if(obtenerIngresoB()<1000){
            return "Ingreso Bruto (Debe ser 1000 o más)";
        }else if(txtcostoc.getText().equals("")){
            return "Costo Computable (Vacio)";
        }else if(txtGastos.getText().equals("")){
            return "Gastos (Vacio)";
        }else if(txtotrosingresos.getText().equals("")){
            return "Otros Ingresos (Vacio)";
        }else if(txtadicionales.getText().equals("")){
            return "Adicionales (Vacio)";
        }else if(txtdeducciones.getText().equals("")){
            return "Deducciones (Vacio)";
        }else if(txtperdidas.getText().equals("")){
            return "Perdidas Tributarias (Vacio)";
        }else if(txtcreditos.getText().equals("")){
            return "Creditos Compensables (Vacio)";
        }else if(obtenerPersona()==-1){
            return "Tipo Persona (Vacio)";
        }else{
            return "";
        }
    }
    private void txtcostocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostocActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(Validar().equals("")){
            TerceraCategoria categoria3 = new TerceraCategoria(obtenerIngresoB(), obtenerCostoC(), obtenerGastos(), obtenerOtros(), obtenerAdicionales(), obtenerDeducciones(), obtenerPerdidas(), obtenerPersona());
            if(categoria3.getImpuesto()==Double.parseDouble(lbRetencion.getText())){
                MostrarValores();
                Usuario unUsuario = new Usuario(Registro.unregistro.getUsuario().getNombre(), Registro.unregistro.getUsuario().getDNI());
                Fecha unaFechaEmi = new Fecha(ObtenerDia(), ObtenerMes(), ObtenerAnio());
                Tributo x = new Tributo(unUsuario, unaFechaEmi);
                x.setContribuyente(unUsuario);
                x.setFechaEmision(unaFechaEmi);
                x.setCategoria3(categoria3);
                a.adicionar(x);
                a.grabar();

                lbingresoB.setText(String.valueOf(x.getCategoria3().getIngresosBrutos()));
                lbcostoC.setText(String.valueOf(x.getCategoria3().getCostoComputable()));
                lbgastos.setText(String.valueOf(x.getCategoria3().getGastos()));
                lbotros.setText(String.valueOf(x.getCategoria3().getOtrosIngresos()));
                lbadicionales.setText(String.valueOf(x.getCategoria3().getAdiciones()));
                lbdeducciones.setText(String.valueOf(x.getCategoria3().getDeducciones()));
                lbperdida.setText(String.valueOf(x.getCategoria3().getPerdidasTributarias()));
                lbrenta.setText(String.valueOf(x.getCategoria3().getRentaNeta()));
                lbRentaB.setText(String.valueOf(x.getCategoria3().getRentaBruta()));
                lbperdida.setText(String.valueOf(x.getCategoria3().getPerdidasTributarias()));
                lbImpuesto.setText(String.valueOf(x.getCategoria3().getImpuesto()));

                PanelMostrar3.setVisible(true);
                PanelReseccion3.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Ha modificado los valores ingresados");
            }
        }else{
            JOptionPane.showMessageDialog(null,"El error esta en "+Validar());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Validar().equals("")){
            TerceraCategoria unacategoria = new TerceraCategoria(obtenerIngresoB(), obtenerCostoC(), obtenerGastos(), obtenerOtros(), obtenerAdicionales(), obtenerDeducciones(), obtenerPerdidas(), obtenerPersona());
            lbRetencion.setText(String.valueOf(unacategoria.getImpuesto()));
            btnGuardar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"El error esta en "+Validar());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMostrar3;
    private javax.swing.JPanel PanelR;
    private javax.swing.JScrollPane PanelReseccion3;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbPersona;
    private com.toedter.calendar.JDateChooser dataEmision;
    private com.toedter.calendar.JDateChooser dataEmision1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbDni;
    private javax.swing.JLabel lbDni1;
    private javax.swing.JLabel lbEdad;
    private javax.swing.JLabel lbEdad1;
    private javax.swing.JLabel lbImpuesto;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JLabel lbRentaB;
    private javax.swing.JLabel lbRetencion;
    private javax.swing.JLabel lbadicionales;
    private javax.swing.JLabel lbcostoC;
    private javax.swing.JLabel lbdeducciones;
    private javax.swing.JLabel lbgastos;
    private javax.swing.JLabel lbingresoB;
    private javax.swing.JLabel lbotros;
    private javax.swing.JLabel lbperdida;
    private javax.swing.JLabel lbrenta;
    private javax.swing.JTextField txtGastos;
    private javax.swing.JTextField txtadicionales;
    private javax.swing.JTextField txtcostoc;
    private javax.swing.JTextField txtcreditos;
    private javax.swing.JTextField txtdeducciones;
    private javax.swing.JTextField txtingresob;
    private javax.swing.JTextField txtotrosingresos;
    private javax.swing.JTextField txtperdidas;
    // End of variables declaration//GEN-END:variables
}
