/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrativo;


import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author bryleo
 */
public class EstaUbi extends javax.swing.JInternalFrame {
    ArregloUbigeo t=new ArregloUbigeo();
    
    /**
     * Creates new form EstaPri
     */
    public EstaUbi() {
        initComponents();
        DefinirAnchos();
        
        CargarDepar();
        
    }
void CargarDepar()
    {
        int codigoDepar=0;
        cbDepar.removeAllItems();
        for(int i=0;i<t.getTamaño();i++) //Va a recorrer el arreglo entero de ubigeo
        {
            if(codigoDepar!=t.obtener(i).getCodigoDepar_Depar()) //Si encuentra un departamento repetido, no lo añade al combobox
            {
                cbDepar.addItem(t.obtener(i).getDepar().toUpperCase());
                codigoDepar=t.obtener(i).getCodigoDepar_Depar();
            }
                
        }
        cbDepar.setSelectedIndex(-1);
    }
String obtenerDepar()
    {
        if(String.valueOf(cbDepar.getSelectedItem()).equals("null"))
        {
            return "-";
        } else return String.valueOf(cbDepar.getSelectedItem()).toUpperCase();
    }
String obtenerProvin()
    {
        if(String.valueOf(cbProvin.getSelectedItem()).equals("null"))
        {
            return "-";
        } else return String.valueOf(cbProvin.getSelectedItem()).toUpperCase();
    }
void limpiaMatriz(){
        for(int i=0;i<100;i++){
            tbResult.setValueAt("", i, 0);
            tbResult.setValueAt("", i, 1);
            tbResult.setValueAt("", i, 2);
            tbResult.setValueAt("", i, 3);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tbResult = new javax.swing.JTable();
        cbDepar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        cbProvin = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("UBIGEOS");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tbResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO"
            }
        ));
        jScrollPane1.setViewportView(tbResult);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 700;
        gridBagConstraints.ipady = 333;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 6);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        cbDepar.setBorder(javax.swing.BorderFactory.createTitledBorder("DEPARTAMENTO"));
        cbDepar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDeparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbDeparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbDeparMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbDeparMousePressed(evt);
            }
        });
        cbDepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeparActionPerformed(evt);
            }
        });
        cbDepar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbDeparKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(cbDepar, gridBagConstraints);

        jButton1.setText("BUSCAR POR DEPARTAMENTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        cbProvin.setBorder(javax.swing.BorderFactory.createTitledBorder("PROVINCIA"));
        cbProvin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbProvinMouseClicked(evt);
            }
        });
        cbProvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProvinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        getContentPane().add(cbProvin, gridBagConstraints);

        jButton2.setText("BUSCAR POR PROVINCIA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        getContentPane().add(jButton2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDeparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDeparMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbDeparMouseClicked

    private void cbDeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeparActionPerformed
        // TODO add your handling code here:
        int codigoProvin=0;
        cbProvin.removeAllItems();
        for(int i=0;i<t.getTamaño();i++)
        {
            if(obtenerDepar().equals(t.obtener(i).getDepar().toUpperCase())&&codigoProvin!=t.obtener(i).getCodigoProvi_Provi())
            {
                cbProvin.addItem(t.obtener(i).getProvi().toUpperCase());
                codigoProvin=t.obtener(i).getCodigoProvi_Provi();
            }
        }
        cbProvin.setSelectedIndex(-1);
    }//GEN-LAST:event_cbDeparActionPerformed

    String conteo(int numero)
    {
        if(numero<10)
            return "0"+numero;
        else return ""+numero;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiaMatriz();
        int cont=0;//para ubicar todos los datos desde el inicio de la tabla
        if (t.getTamaño()>0){
            for(int i=0;i<t.getTamaño();i++){
                Ubigeo ubi=t.obtener(i);
                if(ubi.getDepar().toUpperCase().equals(obtenerDepar()))
                {
                    try{
                        tbResult.setValueAt(conteo(ubi.getCodigoDepar_Depar())+conteo(ubi.getCodigoProvi_Provi())+conteo(ubi.getCodigoDistri_Distri()),cont,0);                
                   
                        tbResult.setValueAt(ubi.getDepar().toUpperCase(), cont, 1);
                        tbResult.setValueAt(ubi.getProvi().toUpperCase(), cont, 2);
                        tbResult.setValueAt(ubi.getDistri().toUpperCase(), cont, 3);
                        cont++;
                    }catch (Exception ex){}
                    
                }
            }
        }
        cbProvin.setSelectedIndex(-1);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbDeparMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDeparMousePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbDeparMousePressed

    private void cbDeparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDeparMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbDeparMouseEntered

    private void cbDeparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDeparMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbDeparMouseExited

    private void cbDeparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbDeparKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cbDeparKeyPressed

    private void cbProvinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProvinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProvinMouseClicked

    private void cbProvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProvinActionPerformed

    }//GEN-LAST:event_cbProvinActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        limpiaMatriz();
        int cont=0;//para ubicar todos los datos desde el inicio de la tabla
        if (t.getTamaño()>0){
            for(int i=0;i<t.getTamaño();i++){
                Ubigeo ubi=t.obtener(i);
                if(ubi.getDepar().toUpperCase().equals(obtenerDepar())&&ubi.getProvi().toUpperCase().equals(obtenerProvin()))
                {
                    tbResult.setValueAt(conteo(ubi.getCodigoDepar_Depar())+conteo(ubi.getCodigoProvi_Provi())+conteo(ubi.getCodigoDistri_Distri()),cont,0);                
                   
                    tbResult.setValueAt(ubi.getDepar().toUpperCase(), cont, 1);
                    tbResult.setValueAt(ubi.getProvi().toUpperCase(), cont, 2);
                    tbResult.setValueAt(ubi.getDistri().toUpperCase(), cont, 3);
                    cont++;
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    void DefinirAnchos(){
        TableColumn columna; //de tipo TableColum
        columna=tbResult.getColumnModel().getColumn(0);//columna 0
        columna.setPreferredWidth(70); //ancho de columna
        columna=tbResult.getColumnModel().getColumn(1);
        columna.setPreferredWidth(200);
        columna=tbResult.getColumnModel().getColumn(2);
        columna.setPreferredWidth(200);
        columna=tbResult.getColumnModel().getColumn(3);
        columna.setPreferredWidth(200);
        
        
        tbResult.getTableHeader().setReorderingAllowed(false); //permite no mover las columnas de su posición actual
        tbResult.getTableHeader().setResizingAllowed(false); //permite no modificar el ancho de las columnas
        
    }
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDepar;
    private javax.swing.JComboBox<String> cbProvin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbResult;
    // End of variables declaration//GEN-END:variables
}
